apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-vpc-creation
  namespace: test-one
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/test-one/dynamic-test.yaml
      repositoryRef: flux-system
  serviceAccountName: gitopssets
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-vpc-dynamic-test-{{ .Repeat.name }}
      spec:
        interval: 1m0s
        path: ./infra/dynamic/vpc-create
        postBuild:
          substitute:
            privateSubnetCount: '{{ getordefault .Repeat "privatesubnets" "3" }}'
            publicSubnetCount: '{{ getordefault .Repeat "publicsubnets" "3" }}'
            region: '{{ .Element.aws.region }}'
            resourceName: dynamic-test
            templateNamespace: test-one
            vpcCIDR: '{{ getordefault .Repeat "cidr"  "10.0.0.0/16"}}'
            vpcName: '{{ .Repeat.name }}'
          substituteFrom:
          - kind: ConfigMap
            name: cluster-config
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 10m
        wait: true
    repeat: '{ .vpcs[?(@.mode=="create")] }'

---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-vpc-discovery
  namespace: test-one
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/test-one/dynamic-test.yaml
      repositoryRef: flux-system
  serviceAccountName: gitopssets
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-vpc-{{ getordefault .Repeat "resource" "dynamic-test"}}-{{
          .Repeat.name }}
      spec:
        interval: 1m0s
        path: ./infra/dynamic/vpc-{{ .Repeat.mode }}
        postBuild:
          substitute:
            resourceName: dynamic-test
            templateNamespace: test-one
            vpcName: '{{ .Repeat.name }}'
            vpcResource: '{{ getordefault .Repeat "resource" "dynamic-test"}}'
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 10m
        wait: true
    repeat: '{ .vpcs[?(@.mode!="create")] }'

---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-gitops-clusters
  namespace: test-one
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/test-one/dynamic-test.yaml
      repositoryRef: flux-system
  serviceAccountName: gitopssets
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-cluster-{{ getordefault .Repeat "resource" "dynamic-test"}}-{{
          .Repeat.name }}-gitops-cluster
      spec:
        interval: 1m0s
        path: ./wge-resources/wge
        postBuild:
          substitute:
            clusterName: '{{ .Repeat.name }}'
            resourceName: dynamic-test
            templateNamespace: test-one
          substituteFrom:
          - kind: ConfigMap
            name: cluster-config
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 1m
    repeat: '{ .clusters[?(@.gui)] }'

---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-eks-cluster-creation
  namespace: test-one
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/test-one/dynamic-test.yaml
      repositoryRef: flux-system
  serviceAccountName: gitopssets
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-eks-dynamic-test-{{ .Repeat.name }}
      spec:
        dependsOn:
        - name: dynamic-test-vpc-{{ getordefault .Repeat "vpc_resource" "dynamic-test"}}-{{
            .Repeat.vpc_name }}
        interval: 1m0s
        path: ./infra/dynamic/eks-create
        postBuild:
          substitute:
            clusterName: '{{ .Repeat.name }}'
            clusterVersion: '{{ .Repeat.version }}'
            resourceName: dynamic-test
            templateNamespace: test-one
            vpcName: '{{ .Repeat.vpc_name }}'
            vpcResource: '{{ getordefault .Repeat "vpc_resource" "dynamic-test"}}'
          substituteFrom:
          - kind: ConfigMap
            name: cluster-config
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 15m
        wait: true
    repeat: '{ .clusters[?(@.mode=="create")] }'

---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-eks-cluster-discovery
  namespace: test-one
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/test-one/dynamic-test.yaml
      repositoryRef: flux-system
  serviceAccountName: gitopssets
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-eks-{{ getordefault .Repeat "resource" "dynamic-test" }}-{{
          .Repeat.name }}
      spec:
        dependsOn:
        - name: dynamic-test-vpc-{{ getordefault .Repeat "vpc_resource" "dynamic-test"
            }}-{{ .Repeat.vpc_name }}
        interval: 1m0s
        path: ./infra/dynamic/eks-{{ .Repeat.mode }}
        postBuild:
          substitute:
            clusterName: '{{ getordefault .Repeat "resource" "dynamic-test" }}-{{
              .Repeat.name }}'
            resourceName: dynamic-test
            templateNamespace: test-one
          substituteFrom:
          - kind: ConfigMap
            name: cluster-config
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 15m
        wait: true
    repeat: '{ .clusters[?(@.mode!="create")] }'

---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-eks-config
  namespace: test-one
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/test-one/dynamic-test.yaml
      repositoryRef: flux-system
  serviceAccountName: gitopssets
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-eks-config-dynamic-test-{{ .Repeat.name }}
      spec:
        dependsOn:
        - name: dynamic-test-eks-dynamic-test-{{ .Repeat.name }}
        interval: 1m0s
        path: ./infra/dynamic/eks-config
        postBuild:
          substitute:
            clusterName: '{{ .Repeat.name }}'
            desired_size: '"2"'
            eks_core_state_bucket: ${prefixName}-${awsAccountId}-${awsRegion}-tf-state
            resourceName: dynamic-test
            target_path: clusters/test-one/dynamic-test/${clusterName}
            templateNamespace: test-one
          substituteFrom:
          - kind: ConfigMap
            name: cluster-config
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 5m
        wait: true
    repeat: '{ .clusters[?(@.mode=="create")] }'
