apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wge-sa
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./leaf-clusters/wge-sa
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      templateNamespace: wge
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wge-leaf-config
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./leaf-clusters/wge-leaf-config
  prune: true
  timeout: 5m
  wait: true
  postBuild:
    substitute:
      clusterName: kind-u2-kind
      GitHubOrg: ww-gitops
      GitHubRepo: paulcarlton-ww-macbook
      userEmail: paul.carlton@weave.works
      commitUser: paulcarlton-ww
      resourceName: kind
      templateNamespace: wge
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wge-leaf
  namespace: wge
spec:
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true
  dependsOn:
  - name: wge-leaf-config
  - name: wge-sa
  interval: 5m0s
  path: ./leaf-clusters/wge-leaf
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wge-leaf-apps
  namespace: wge
spec:
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true
  dependsOn:
  - name: wge-leaf
  interval: 5m0s
  path: ./leaf-clusters/wge-leaf-apps
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config