---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSClusterStaticIdentity
metadata:
  name: capi-aws-creds
  namespace: ${nameSpace}
spec:
  allowedNamespaces:
    list:
    - ${nameSpace}
  secretRef: capi-aws-creds