---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: templates
  namespace: flux-system
spec:
  dependsOn:
    - name: apps
  interval: 10m0s
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: /templates
  prune: true
  wait: false
