apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-c1-kubeconfig
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: test-c1-kubeconfig
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: leaf-clusters/test-c1-kubeconfig
