---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wge-oidc-auth
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: wge-oidc-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: terraform-repo-read-credentials

