apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops-enterprise-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.dev.wkp.weave.works/releases/charts-v3
  secretRef:
    name: weave-gitops-enterprise-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-enterprise
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mccp
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-enterprise-charts
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 1m0s
  timeout: 5m
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      tls:
        - secretName: wge-tls
          hosts:
            - wge.${hostName}
      hosts:
        - host: wge.${hostName}
          paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
    config:
      git:
        type: github
        hostname: github.com
      capi:
        repositoryURL: https://github.com/${githubOrg}/${githubRepo}
      oidc:
        enabled: true
        issuerURL: https://dex.${hostName}
        redirectURL: https://wge.${hostName}/oauth2/callback
        clientCredentialsSecret: wge-oidc-auth
    policy-agent:
      enabled: true
      excludeNamespaces:
        - flux-system
        - kube-system
      config:
        clusterId: macbook
    tls:
      enabled: false
    enablePipelines: true
    enableTerraformUI: true
    global:
      capiEnabled: false

  
