apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 1m0s
  timeout: 5m
  values:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: external
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          external-dns.alpha.kubernetes.io/hostname: ${hostName}
      ingressClassResource:
        default: true
  postRenderers:
    - kustomize:
        # patchesJson6902:
        patches:
        - target:
            kind: Deployment
            name: ingress-nginx-controller
          patch: |-
            - op: add
              path: /spec/template/spec/hostAliases
              value:
                - ip: ${clusterIP}
                  hostnames:
                  - "dex.${hostName}"
                  - "wge.${hostName}"

            - op: add
              path: /spec/template/spec/volumes/-
              value:
                name: local-ca
                configMap:
                  name: local-ca

            - op: add
              path: /spec/template/spec/containers/0/volumeMounts/-
              value:
                name: local-ca
                mountPath: /etc/ssl/certs/local-ca.pem
                subPath: CA.cer
                readOnly: false