apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    templates.weave.works/template-name: aws-eks-dev
    templates.weave.works/template-namespace: ""
    weave.works/capi: bootstrap
  name: capi1
  namespace: default
spec:
  capiClusterRef:
    name: capi1

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: aws-eks-dev
    templates.weave.works/template-namespace: ""
  name: capi1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.120.0.0/20
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: capi1-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: capi1-control-plane

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aws-eks-dev
    templates.weave.works/template-namespace: ""
  name: capi1-control-plane
  namespace: default
spec:
  additionalTags:
    creator: ${awsTagCustomer}
    customer: ${awsTagProjectGid}
    projectGid: ${awsTagCreator}
  addons:
  - conflictResolution: overwrite
    name: vpc-cni
    version: v1.12.6-eksbuild.2
  eksClusterName: capi1
  region: eu-west-1
  sshKeyName: ${awsKeyPairName}
  version: ${KUBERNETES_VERSION}

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aws-eks-dev
    templates.weave.works/template-namespace: ""
  name: capi1-pool-0
  namespace: default
spec:
  clusterName: capi1
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: capi1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: capi1-pool-0

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aws-eks-dev
    templates.weave.works/template-namespace: ""
  name: capi1-pool-0
  namespace: default
spec:
  remoteAccess:
    public: true
  scaling:
    maxSize: 3
    minSize: 1
  updateConfig:
    maxUnavailable: 1
