apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-vpcs
  namespace: default
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/default/dynamic-test.yaml
      repositoryRef: flux-system
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-vpc-dynamic-test-{{ .Repeat.name }}
      spec:
        interval: 1m0s
        path: ./infra/dynamic/vpc-create
        postBuild:
          substitute:
            privateSubnetCount: '{{ or .Repeat.privatesubnets "3" }}'
            publicSubnetCount: '{{ or .Repeat.publicsubnets "3" }}'
            region: '{{ .Element.aws.region }}'
            resourceName: dynamic-test
            templateNamespace: default
            vpcCIDR: '{{ or .Repeat.cidr  "10.0.0.0/16"}}'
            vpcName: '{{ .Repeat.name }}'
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 10m
        wait: true
    repeat: '{ .vpcs }'

---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-gitops-clusters
  namespace: default
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/default/dynamic-test.yaml
      repositoryRef: flux-system
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-cluster-{{ .Repeat.name }}-gitops-cluster
      spec:
        interval: 1m0s
        path: ./clusters/wge
        postBuild:
          substitute:
            clusterName: '{{ .Repeat.name }}'
            resourceName: dynamic-test
            templateNamespace: default
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 1m
    repeat: '{ .clusters[?(@.gui)] }'

---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-eks-clusters
  namespace: default
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/default/dynamic-test.yaml
      repositoryRef: flux-system
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-eks-dynamic-test-{{ .Repeat.name }}
      spec:
        dependsOn:
        - name: dynamic-test-vpc-{{ .Repeat.vpc_name }}
        interval: 1m0s
        path: ./infra/dynamic/eks-{{ .Repeat.mode }}
        postBuild:
          substitute:
            clusterName: '{{ .Repeat.name }}'
            clusterVersion: '{{ .Repeat.version }}'
            resourceName: dynamic-test
            templateNamespace: default
            vpcName: '{{ .Repeat.vpc_name }}'
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 15m
        wait: true
    repeat: '{ .clusters }'

---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-eks-config
  namespace: default
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/default/dynamic-test.yaml
      repositoryRef: flux-system
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-eks-config-dynamic-test-{{ .Repeat.name }}
      spec:
        dependsOn:
        - name: dynamic-test-eks-dynamic-test-{{ .Repeat.name }}
        interval: 1m0s
        path: ./infra/dynamic/eks-config
        postBuild:
          substitute:
            clusterName: '{{ .Repeat.name }}'
            desired_size: '"2"'
            eks_core_state_bucket: ${prefixName}-${awsAccountId}-${awsRegion}-tf-state
            resourceName: dynamic-test
            target_path: clusters/default/dynamic-test/${clusterName}
            templateNamespace: default
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 5m
        wait: true
    repeat: '{ .clusters[?(@.mode=="create")] }'

---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/created-by: gitopssets-controller
    app.kubernetes.io/instance: gitopsset-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/part-of: gitopssets-controller
    templates.weave.works/template-name: dynamic-v1
    templates.weave.works/template-namespace: ""
  name: dynamic-test-apps
  namespace: default
spec:
  generators:
  - gitRepository:
      files:
      - path: resource-descriptions/default/dynamic-test.yaml
      repositoryRef: flux-system
  templates:
  - content:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        annotations:
          templates.weave.works/create-request: ""
        name: dynamic-test-cluster-{{ .Element.name }}-app-{{ .Repeat.name }}
      spec:
        interval: 1m0s
        path: ./cluster/apps/template
        postBuild:
          substitute:
            appName: '{{ .Repeat.name }}'
            appPath: '{{or .Repeat.path "./kustomize" }}'
            appRefType: '{{or .Repeat.ref.type "branch" }}'
            appRefValue: '{{or .Repeat.ref.value "main" }}'
            appVersion: '{{or .Repeat.version "" }}'
            clusterName: '{{ .Element.name }}'
            resourceName: dynamic-test
            templateNamespace: default
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        timeout: 5m
        wait: true
    repeat: '{ .clusters.apps }'
