---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: flux-system
data:
  clusterType: "macbook"
  clusterName: ww-paulc-macbook
  clusterIP: 10.110.112.126
  GitHubOrg: ww-gitops
  GitHubRepo: paulcarlton-ww-macbook
  awsAccountId: "\"749339757188\""
  prefixName: ww-paulc
  awsRegion: eu-west-1
  awsTagCreator: paul.carlton@weave.works
  awsTagCustomer: weaveworks-cx
  awsTagProjectGid: "\"20276\""
