---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  clusterType: "macbook"
  clusterName: ww-paulc-macbook
  clusterIP: 10.107.53.118
  GitHubOrg: ww-gitops
  GitHubRepo: paulcarlton-ww-macbook
  awsAccountId: ac-749339757188
  prefixName: ww-paulc
  awsRegion: eu-west-1
  awsTagCreator: paul.carlton@weave.works
  awsTagCustomer: weaveworks-cx
  awsTagProjectGid: "20276"
