apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  labels:
    app.kubernetes.io/name: gitopsset
    app.kubernetes.io/instance: gitopsset-namespace
    app.kubernetes.io/part-of: gitopssets-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gitopssets-controller
  name: namespaces
  namespace: flux-system
spec:
  serviceAccountName: gitopssets
  generators:
    - gitRepository:
        repositoryRef: flux-system
        files:
          - path: resource-descriptions/namespaces.yaml
  templates:
    - repeat: '{ .namespaces }'
      content:
        kind: Kustomization
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        metadata:
          name: 'namespace-{{ .Repeat.name }}'
          annotations:
            templates.weave.works/create-request: ''
        spec:
          interval: 1m0s
          sourceRef:
            kind: GitRepository
            name: flux-system
            namespace: flux-system
          path: ./cluster/namespaces
          prune: true
          wait: true
          timeout: 10m
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-config
            substitute:
              nameSpace: '{{ .Repeat.name }}'
              hostname: ${hostName}
              limitsCpu: '{{ or .Repeat.quota.limits.cpu .Element.default.quota.limits.cpu }}'
              limitsMemory: '{{ or .Repeat.quota.limits.memory .Element.default.quota.limits.memory }}'
              requestsCpu: '{{ or .Repeat.quota.requests.cpu .Element.default.quota.requests.cpu }}'
              requestsMemory: '{{ or .Repeat.quota.requests.memory .Element.default.quota.requests.memory }}'
              pods: '{{ or .Repeat.quota.pods .Element.default.quota.pods }}'
              # podLimitsMaxCpu: '{{ or .Repeat.limits["Pod"].max.cpu .Element.limits["Pod"].max.cpu }}'
