apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: '${resourceName}-vpc-${vpcResource}-${vpcName}'
  namespace: ${templateNamespace}
spec:
  interval: 10m
  retryInterval: 20s
  path: ./terraform/cluster-templates/vpc-use
  approvePlan: auto
  destroyResourcesOnDeletion: true
  writeOutputsToSecret:
    name: '${resourceName}-vpc-${vpcResource}-${vpcName}-config'
  backendConfig:
    customConfiguration: |
      backend "s3" {
        key            = "${clusterName}/${templateNamespace}/${resourceName}/vpc/${vpcResource}-${vpcName}/terraform.tfstate"
        bucket         = "${prefixName}-${awsAccountId}-${awsRegion}-tf-state"
        region         = "${awsRegion}"
        encrypt        = true
        dynamodb_table = "${prefixName}-${awsAccountId}-${awsRegion}-tf-state"
      }
  vars:
    - name: vpc_name
      value: ${vpcResource}-${vpcName}
    - name: region
      value: ${awsRegion}
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-creds