apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: '${resourceName}-eks-${clusterName}'
  namespace: ${templateNamespace}
spec:
  interval: 1h
  retryInterval: 20s
  path: ./cluster-templates/eks-use
  approvePlan: auto
  destroyResourcesOnDeletion: true
  writeOutputsToSecret:
    name: '${resourceName}-eks-${clusterName}-config'
  dependsOn:
    - name: '${resourceName}-vpc-${vpcName}'
  backendConfig:
    customConfiguration: |
      backend "s3" {
        key            = "${clusterName}/${templateNamespace}/${resourceName}/eks/${clusterName}/terraform.tfstate"
        bucket         = "${prefixName}-${awsAccountId}-${awsRegion}-tf-state"
        region         = "${awsRegion}"
        encrypt        = true
        dynamodb_table = "${prefixName}-${awsAccountId}-${awsRegion}-tf-state"
      }
  vars:
    - name: cluster_name
      value: ${clusterName}
    - name: region
      value: ${awsRegion}    
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
