---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/addons/cert-manager
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/addons/nginx
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      hostName: kubernetes.docker.internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/addons/reloader
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-config
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/cert-config
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager
    - name: nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      hostName: kubernetes.docker.internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/addons/vault
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      hostName: kubernetes.docker.internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/addons/external-secrets
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/secrets
  prune: true
  wait: true
  dependsOn:
    - name: external-secrets
    - name: cert-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      hostName: kubernetes.docker.internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: vault
    - name: secrets
  path: ./cluster/addons/dex
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      hostName: kubernetes.docker.internal
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/config
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: secrets
  path: ./cluster/addons/tf-controller
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wge
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: dex
  path: ./cluster/addons/wge
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      hostName: kubernetes.docker.internal
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prom-graf
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: secrets
  path: ./cluster/addons/prom-graf
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      hostName: kubernetes.docker.internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wge-rbac
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: wge
  path: ./cluster/bases
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wge-templates
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: wge
  path: ./cluster/wge-templates
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

