#
# External Secrets
#
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-key-pair
  namespace: cert-manager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ca-key-pair
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ca-key-pair

