#
# External Secrets
#
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-key-pair
  namespace: cert-manager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ca-key-pair
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ca-key-pair
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-config
  namespace: dex
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: dex-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dex-config
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wge-oidc-auth
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: wge-oidc-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: wge-oidc-auth


