apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.vault.svc.cluster.local:8200 # https://vault.${hostName} 
      path: secrets
      version: v2
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "vault"
          key: "vault-token"
      #   kubernetes:
      #     mountPath: weaveworks
      #     role: external-secrets-vault
      #     serviceAccountRef:
      #       name: vault-secrets-sa
      #       namespace: flux-system
        # appRole:
        #   # Path where the App Role authentication backend is mounted
        #   path: "approle"
        #   # RoleID configured in the App Role authentication backend
        #   roleId: "db02de05-fa39-4855-059b-67221c5c2f63"
        #   # Reference to a key in a K8 Secret that contains the App Role SecretId
        #   secretRef:
        #     name: "approle"
        #     namespace: "vault"
        #     key: "secret-id"

