---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSClusterStaticIdentity
metadata:
  name: capi-aws-creds
  namespace: default
spec:
  allowedNamespaces:
    list:
    - default
  secretRef: capi-aws-creds