---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: aws-key-pair
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 20s
  path: ./terraform/cluster-templates/aws-key-pair
  approvePlan: auto
  destroyResourcesOnDeletion: true
  backendConfig:
    customConfiguration: |
      backend "s3" {
        key            = "${mgmtClusterName}/flux-system/aws-key-pair/${keyPairName}/terraform.tfstate"
        bucket         = "${prefixName}-${awsAccountId}-${awsRegion}-tf-state"
        region         = "${awsRegion}"
        encrypt        = true
        dynamodb_table = "${prefixName}-${awsAccountId}-${awsRegion}-tf-state"
      }
  vars:
    - name: tags
      value:
        customer: ${awsTagCustomer}
        projectGid: ${awsTagProjectGid}
        creator: ${awsTagCreator}
  varsFrom:
    - kind: ConfigMap
      name: cluster-config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-creds
